name: Terraform CI/CD

## Github Actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Plan, Apply, and Destroy
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: "concepts-demo"
          credentials_json: ${{ secrets.NG_SA_KEY_GCLOUD }}

      # Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      # Terraform init
      - name: Initialize Terraform
        run: terraform init

      # Terraform plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Terraform apply (Only on push events to main)
      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve tfplan

      # Wait for 1 minute
      - name: Wait for 1 minute
        run: sleep 60

      # Terraform destroy
      - name: Terraform Destroy
        if: github.event_name == 'push'
        run: terraform destroy -auto-approve
